name: ESP32 Arduino Release

on:
  release:
    types: published

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./.github/scripts/on-release.sh
